### ISSUE TITLE
Request to update symfony/mailgun-mailer to v.6.3.5

### ISSUE THREAD

**Issue by Romanavr** [craftcms/mailgun#33]
We recently noticed a [bug with the Outlook sender](https://github.com/symfony/symfony/issues/51596) and fixed it via [PR to the symfony/mailgun-mailer](https://github.com/symfony/symfony/pull/51773) repo.
It was merged and [released with v6.3.5](https://github.com/symfony/mailgun-mailer/commit/b467aba49c8240a71f7027c213d9d140ba1abce7).

Could you guys update the version of `symfony/mailgun-mailer` in composer?

**Comment by angrybrad** [comment]
@Romanavr looks like symfony mailgun-mailer bumped the minimum PHP requirement in the 6.1 release to 8.1 https://github.com/symfony/mailgun-mailer/blob/6.1/composer.json#L19

It's probably not something we want to do in Craft 4 since it still supports 8.0.2, but we could go up to the 6.3.x release in the upcoming Craft 5 compatible release since that requires PHP 8.2.

**Comment by Romanavr** [comment]
> @Romanavr looks like symfony mailgun-mailer bumped the minimum PHP requirement in the 6.1 release to 8.1 https://github.com/symfony/mailgun-mailer/blob/6.1/composer.json#L19
> 
> It's probably not something we want to do in Craft 4 since it still supports 8.0.2, but we could go up to the 6.3.x release in the upcoming Craft 5 compatible release since that requires PHP 8.2.

Just curious, do you have an approximate release date for Craft 5? Like Q3 of 2024?

**Comment by angrybrad** [comment]
@Romanavr yes! the dev preview is out now, beta by the end of the year and GA release Q1 2024.
